fix(shortcuts): always unregister global shortcuts before reregistering Fixes an error where I was getting
```
TypeError: window['_3282349814'] is not a function. (In 'window['_3282349814']({ message: {"shortcut":"shift+super+KeyD","id":570425366,"state":"Pressed"}, index: 14 })', 'window['_3282349814']' is undefined)
```

since the old callback registered was somehow being lost on full page refreshes. Unregistering before reregistering fixes this.


Former-commit-id: 19f6380453a9b5dc1c842bb28bfe826889184c9b [formerly c9d40de3566307ed704868b913390398e1125158 [formerly c9d40de3566307ed704868b913390398e1125158 [formerly bfc7c2fe6aa3fd9f754e9026a464f56d7a11adcf]]]
Former-commit-id: f0f83a97c239db42a98c5f9dabbf30d949baa3fd
Former-commit-id: 0ec411f25bb2848bdf93b6c1ae3c18bf0c7b23f9
Former-commit-id: beee300c6725f10b1a281b1c0efc1bfe98d30b21